jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Java JDK and Maven
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_SECRET }}
        java-version: '8'
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Configure Git user
      run: 'git config user.email "actions@github.com"

        git config user.name "GitHub Actions"

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWD }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWD }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
      name: Publish package
      run: 'cd spring-cloud-starter-baidu-starlight

        mvn -B release:prepare release:perform -P deploy -Darguments="-Dmaven.test.skip"
        -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{
        github.event.inputs.developmentVersion }} --no-transfer-progress

        '
    - continue-on-error: true
      id: changelog
      name: Generate changelog
      uses: metcalfc/changelog-generator@v4.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        body: '### Things that changed in this release

          ${{ steps.changelog.outputs.changelog }}

          '
        draft: true
        prerelease: false
        release_name: starter-v${{ github.event.inputs.releaseVersion }}
        tag_name: starter-v${{ github.event.inputs.releaseVersion }}
name: Starlight Starter Release
on:
  repository_dispatch:
    types: trigger-ga___starlight-starter-release.yml
